import { useState } from "react"
import { motion } from "framer-motion"

const nav = ["My Quotation", "Messages", "Profile"]
export default function CustomerPortal() {
  const [active, setActive] = useState("My Quotation")
  const [message, setMessage] = useState("")
  const [messages, setMessages] = useState([{ sender: "DealFlow360 team", time: "Today, 10:24 AM", text: "Your updated quotation Q-1042 is ready to review.", attachment: "Q-1042-revision.pdf" }])
  const [notice, setNotice] = useState("")
  const [changeRequest, setChangeRequest] = useState(false)
  const [changeComment, setChangeComment] = useState("")
  const send = (event: React.FormEvent) => { event.preventDefault(); if (!message.trim()) return; setMessages([...messages, { sender: "You", time: "Just now", text: message, attachment: "" }]); setMessage("") }
  return <div style={{ minHeight: "100%", padding: 28, maxWidth: 1100, margin: "0 auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", paddingBottom: 16, borderBottom: "1px solid #1a1a1a" }}><div><div style={{ color: "#fff", fontWeight: 700, fontSize: 14 }}>DealFlow360 <span style={{ color: "#666", fontWeight: 500 }}>Customer portal</span></div><div style={{ color: "#666", fontSize: 12, marginTop: 4 }}>Acme Corp</div></div><div style={{ color: "#aaa", fontSize: 12 }}>Rajesh Kumar</div></header>
    <nav style={{ display: "flex", gap: 4, borderBottom: "1px solid #1a1a1a", marginBottom: 24 }}>{nav.map((item) => <button key={item} onClick={() => setActive(item)} style={{ border: 0, borderBottom: active === item ? "2px solid #fff" : "2px solid transparent", background: "none", color: active === item ? "#fff" : "#666", padding: "12px 10px 10px", font: "600 12px Inter", cursor: "pointer" }}>{item}</button>)}</nav>
    {active === "My Quotation" && <section className="df-card" style={{ maxWidth: 850, overflow: "hidden" }}><div style={{ padding: "16px 18px", borderBottom: "1px solid #1d1d1d", display: "flex", justifyContent: "space-between", gap: 16 }}><div><div className="mono" style={{ color: "#fff", fontWeight: 700 }}>Q-1042</div><div style={{ color: "#888", fontSize: 12, marginTop: 4 }}>Acme Corp · Valid through Sep 30</div></div><span style={badge}>Pending your acceptance</span></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", minWidth: 600, borderCollapse: "collapse" }}><thead><tr>{["Product", "Qty", "Price", "Discount", "Total"].map((x) => <th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{[["Laptop Pro 14", "2", "$1,200", "12%", "$2,112"], ["Onsite Setup Service", "1", "$450", "18%", "$369"], ["Extended Warranty", "1", "$180", "10%", "$162"]].map((row) => <tr key={row[0]} style={{ borderTop: "1px solid #171717" }}>{row.map((x, i) => <td key={x} className={i === 4 ? "mono" : ""} style={{ padding: "13px 16px", color: i === 0 || i === 4 ? "#fff" : "#999", fontSize: 12, fontWeight: i === 0 || i === 4 ? 600 : 400 }}>{x}</td>)}</tr>)}</tbody></table></div><div style={{ padding: 18, borderTop: "1px solid #1d1d1d", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, flexWrap: "wrap" }}><div><div style={{ color: "#666", fontSize: 11 }}>Quotation total</div><div className="mono" style={{ color: "#fff", fontSize: 20, fontWeight: 800, marginTop: 3 }}>$2,643</div></div><div style={{ display: "flex", gap: 8 }}><button className="df-btn-secondary" onClick={() => setActive("Messages")}>Send Message</button><button className="df-btn-secondary" onClick={() => setChangeRequest(true)}>Request Changes</button><button className="df-btn-secondary" onClick={() => setNotice("Quotation Q-1042 marked Customer Rejected. The deal is now lost.")}>Reject</button><button className="df-btn-primary" onClick={() => setNotice("Customer Accepted → Q-1042 continues to the approval and fulfillment workflow.")}>Accept</button></div></div>{changeRequest && <form onSubmit={(e) => { e.preventDefault(); setChangeRequest(false); setNotice("Customer Requested Changes → returned to Quotation Detail.") }} style={{ display: "flex", gap: 8, padding: "0 18px 18px" }}><input className="df-input" value={changeComment} onChange={(e) => setChangeComment(e.target.value)} placeholder="Change request / comment" required style={{ flex: 1, height: 35, padding: "8px 10px", fontSize: 12 }}/><button className="df-btn-primary">Submit Changes</button></form>}{notice && <div style={{ margin: "0 18px 18px", color: "#10B981", fontSize: 12 }}>{notice}</div>}</section>}
    {active === "Messages" && <section className="df-card" style={{ maxWidth: 720, overflow: "hidden" }}><div style={{ padding: "14px 16px", borderBottom: "1px solid #1a1a1a", color: "#fff", fontSize: 13, fontWeight: 600 }}>Messages</div><div style={{ padding: 16, display: "grid", gap: 12, minHeight: 220 }}>{messages.map((item, i) => <div key={i} style={{ maxWidth: "80%", marginLeft: item.sender === "You" ? "auto" : 0, background: item.sender === "You" ? "#fff" : "#171717", color: item.sender === "You" ? "#000" : "#ddd", borderRadius: 6, padding: "10px 12px", fontSize: 12 }}><div style={{ fontWeight: 700, fontSize: 11 }}>{item.sender} <span style={{ fontWeight: 400, opacity: .65 }}>· {item.time}</span></div><div style={{ marginTop: 5 }}>{item.text}</div>{item.attachment && <div style={{ marginTop: 8, fontSize: 11, opacity: .75 }}>⌕ Attachment · {item.attachment}</div>}</div>)}</div><form onSubmit={send} style={{ display: "flex", gap: 8, padding: 12, borderTop: "1px solid #1a1a1a" }}><input className="df-input" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write a message…" style={{ flex: 1, height: 36, padding: "8px 10px", fontSize: 12 }}/><button className="df-btn-primary">Send</button></form></section>}
    {active === "Profile" && <Profile />}
  </div>
}
function Profile() { const [saved, setSaved] = useState(false); return <form className="df-card" onSubmit={(e) => { e.preventDefault(); setSaved(true) }} style={{ padding: 18, maxWidth: 650 }}><h1 style={{ margin: "0 0 16px", color: "#fff", fontSize: 16 }}>Profile</h1><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{[["Company Name", "Acme Corp"], ["Contact Name", "Rajesh Kumar"], ["Email", "rajesh@acme.com"], ["Phone", "+1 415 555 0148"], ["Billing Info", "100 Market St, San Francisco, CA"]].map(([label, value]) => <label key={label} style={{ display: "grid", gap: 6, color: "#777", fontSize: 11 }}>{label}<input className="df-input" defaultValue={value} style={{ height: 36, padding: "8px 10px", fontSize: 12 }}/></label>)}</div><div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 16 }}><button className="df-btn-primary">Save</button>{saved && <span style={{ color: "#10B981", fontSize: 12 }}>Profile saved</span>}</div></form> }
const th = { color: "#555", fontSize: 10, textAlign: "left" as const, textTransform: "uppercase" as const, letterSpacing: ".07em", padding: "10px 16px" }; const badge = { display: "inline-flex", height: "fit-content", color: "#F59E0B", background: "rgba(245,158,11,.08)", border: "1px solid rgba(245,158,11,.2)", borderRadius: 4, padding: "4px 7px", fontSize: 11, fontWeight: 600 }
