"""add_g20_scheduled_reports_table

Revision ID: 071fe1c04e2f
Revises: 28259ff8cd65
Create Date: 2026-09-06 06:41:42.911359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071fe1c04e2f'
down_revision: Union[str, Sequence[str], None] = '28259ff8cd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_scheduled_reports_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scheduled_reports_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_reports'))
    )
    op.create_index(op.f('ix_scheduled_reports_company_id'), 'scheduled_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_is_active'), 'scheduled_reports', ['is_active'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_report_type'), 'scheduled_reports', ['report_type'], unique=False)
    op.create_table('report_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_report_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_report_executions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_report_id'], ['scheduled_reports.id'], name=op.f('fk_report_executions_scheduled_report_id_scheduled_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_executions'))
    )
    op.create_index(op.f('ix_report_executions_company_id'), 'report_executions', ['company_id'], unique=False)
    op.create_index(op.f('ix_report_executions_executed_at'), 'report_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_report_executions_report_type'), 'report_executions', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_executions_scheduled_report_id'), 'report_executions', ['scheduled_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_executions_scheduled_report_id'), table_name='report_executions')
    op.drop_index(op.f('ix_report_executions_report_type'), table_name='report_executions')
    op.drop_index(op.f('ix_report_executions_executed_at'), table_name='report_executions')
    op.drop_index(op.f('ix_report_executions_company_id'), table_name='report_executions')
    op.drop_table('report_executions')
    op.drop_index(op.f('ix_scheduled_reports_report_type'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_is_active'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_company_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    # ### end Alembic commands ###
