"""add_b08_recommendation_events_table

Revision ID: 1e5fe8eb16c3
Revises: ed5e9db9b059
Create Date: 2026-09-06 01:32:40.816378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e5fe8eb16c3'
down_revision: Union[str, Sequence[str], None] = 'ed5e9db9b059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quote_reference', sa.String(length=100), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_recommendation_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_recommendation_events_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_recommendation_events_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_recommendation_events_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_events'))
    )
    op.create_index('ix_rec_events_company_created', 'recommendation_events', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_rec_events_company_type_event', 'recommendation_events', ['company_id', 'recommendation_type', 'event_type'], unique=False)
    op.create_index(op.f('ix_recommendation_events_company_id'), 'recommendation_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_customer_id'), 'recommendation_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_event_type'), 'recommendation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_recommendation_events_product_id'), 'recommendation_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_quote_reference'), 'recommendation_events', ['quote_reference'], unique=False)
    op.create_index(op.f('ix_recommendation_events_recommendation_id'), 'recommendation_events', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_recommendation_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_quote_reference'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_product_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_event_type'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_customer_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_company_id'), table_name='recommendation_events')
    op.drop_index('ix_rec_events_company_type_event', table_name='recommendation_events')
    op.drop_index('ix_rec_events_company_created', table_name='recommendation_events')
    op.drop_table('recommendation_events')
    # ### end Alembic commands ###
