"""add_g24_applied_discounts_phase_120

Revision ID: 3aaf9c072397
Revises: 461e92abff83
Create Date: 2026-09-05 18:08:25.424318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aaf9c072397'
down_revision: Union[str, Sequence[str], None] = '461e92abff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('deal_reference', sa.String(length=100), nullable=True),
    sa.Column('decision_id', sa.String(length=100), nullable=True),
    sa.Column('requested_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applied_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discounted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('applied_discount >= 0 AND applied_discount <= 100', name=op.f('ck_applied_discounts_ck_applied_discount_applied_range')),
    sa.CheckConstraint('requested_discount >= 0 AND requested_discount <= 100', name=op.f('ck_applied_discounts_ck_applied_discount_requested_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_applied_discounts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_applied_discounts_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_applied_discounts_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applied_discounts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applied_discounts'))
    )
    op.create_index('ix_applied_discounts_company_deal_product', 'applied_discounts', ['company_id', 'deal_reference', 'product_id'], unique=False)
    op.create_index(op.f('ix_applied_discounts_company_id'), 'applied_discounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_applied_discounts_customer_id'), 'applied_discounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_applied_discounts_deal_reference'), 'applied_discounts', ['deal_reference'], unique=False)
    op.create_index(op.f('ix_applied_discounts_decision_id'), 'applied_discounts', ['decision_id'], unique=False)
    op.create_index(op.f('ix_applied_discounts_product_id'), 'applied_discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_applied_discounts_user_id'), 'applied_discounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applied_discounts_user_id'), table_name='applied_discounts')
    op.drop_index(op.f('ix_applied_discounts_product_id'), table_name='applied_discounts')
    op.drop_index(op.f('ix_applied_discounts_decision_id'), table_name='applied_discounts')
    op.drop_index(op.f('ix_applied_discounts_deal_reference'), table_name='applied_discounts')
    op.drop_index(op.f('ix_applied_discounts_customer_id'), table_name='applied_discounts')
    op.drop_index(op.f('ix_applied_discounts_company_id'), table_name='applied_discounts')
    op.drop_index('ix_applied_discounts_company_deal_product', table_name='applied_discounts')
    op.drop_table('applied_discounts')
    # ### end Alembic commands ###
