"""add_b05_approval_policies_phase_146

Revision ID: 3d9772928f35
Revises: 3aaf9c072397
Create Date: 2026-09-06 00:23:47.649297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d9772928f35'
down_revision: Union[str, Sequence[str], None] = '3aaf9c072397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('levels_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chains_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_policies_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_approval_policies_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_policies'))
    )
    op.create_index('ix_approval_policies_company_active', 'approval_policies', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_approval_policies_company_default', 'approval_policies', ['company_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_approval_policies_company_id'), 'approval_policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_approval_policies_is_active'), 'approval_policies', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_policies_is_active'), table_name='approval_policies')
    op.drop_index(op.f('ix_approval_policies_company_id'), table_name='approval_policies')
    op.drop_index('ix_approval_policies_company_default', table_name='approval_policies')
    op.drop_index('ix_approval_policies_company_active', table_name='approval_policies')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
