"""add_g22_discount_governance_engine_phases_106_110

Revision ID: 461e92abff83
Revises: 642847a0a7ce
Create Date: 2026-09-05 17:40:11.304769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461e92abff83'
down_revision: Union[str, Sequence[str], None] = '642847a0a7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_authority_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_authorized_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_finance_authority_limits_ck_finance_auth_limit_effective_dates')),
    sa.CheckConstraint('max_authorized_discount >= 0 AND max_authorized_discount <= 100', name=op.f('ck_finance_authority_limits_ck_finance_auth_limit_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_authority_limits_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_finance_authority_limits_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finance_authority_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_authority_limits'))
    )
    op.create_index(op.f('ix_finance_authority_limits_company_id'), 'finance_authority_limits', ['company_id'], unique=False)
    op.create_index(op.f('ix_finance_authority_limits_is_active'), 'finance_authority_limits', ['is_active'], unique=False)
    op.create_index(op.f('ix_finance_authority_limits_user_id'), 'finance_authority_limits', ['user_id'], unique=False)
    op.create_index('uq_finance_auth_limits_active', 'finance_authority_limits', ['company_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('manager_authority_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_authorized_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_manager_authority_limits_ck_manager_auth_limit_effective_dates')),
    sa.CheckConstraint('max_authorized_discount >= 0 AND max_authorized_discount <= 100', name=op.f('ck_manager_authority_limits_ck_manager_auth_limit_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_manager_authority_limits_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_manager_authority_limits_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manager_authority_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_authority_limits'))
    )
    op.create_index(op.f('ix_manager_authority_limits_company_id'), 'manager_authority_limits', ['company_id'], unique=False)
    op.create_index(op.f('ix_manager_authority_limits_is_active'), 'manager_authority_limits', ['is_active'], unique=False)
    op.create_index(op.f('ix_manager_authority_limits_user_id'), 'manager_authority_limits', ['user_id'], unique=False)
    op.create_index('uq_manager_auth_limits_active', 'manager_authority_limits', ['company_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_manager_auth_limits_active', table_name='manager_authority_limits', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_manager_authority_limits_user_id'), table_name='manager_authority_limits')
    op.drop_index(op.f('ix_manager_authority_limits_is_active'), table_name='manager_authority_limits')
    op.drop_index(op.f('ix_manager_authority_limits_company_id'), table_name='manager_authority_limits')
    op.drop_table('manager_authority_limits')
    op.drop_index('uq_finance_auth_limits_active', table_name='finance_authority_limits', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_finance_authority_limits_user_id'), table_name='finance_authority_limits')
    op.drop_index(op.f('ix_finance_authority_limits_is_active'), table_name='finance_authority_limits')
    op.drop_index(op.f('ix_finance_authority_limits_company_id'), table_name='finance_authority_limits')
    op.drop_table('finance_authority_limits')
    # ### end Alembic commands ###
