"""add_g16_portal_models

Revision ID: 5eeb7dc444e7
Revises: d16bd718964d
Create Date: 2026-09-06 04:36:14.168539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eeb7dc444e7'
down_revision: Union[str, Sequence[str], None] = 'd16bd718964d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_notifications_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_notifications_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_notifications'))
    )
    op.create_index(op.f('ix_customer_notifications_company_id'), 'customer_notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_notifications_customer_id'), 'customer_notifications', ['customer_id'], unique=False)
    op.create_table('negotiation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_negotiation_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_negotiation_history_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_negotiation_history_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiation_history'))
    )
    op.create_index(op.f('ix_negotiation_history_company_id'), 'negotiation_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_negotiation_history_customer_id'), 'negotiation_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_negotiation_history_quotation_id'), 'negotiation_history', ['quotation_id'], unique=False)
    op.create_table('customer_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('quotation_line_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_customer_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_comments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_comments_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_customer_comments_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_line_items.id'], name=op.f('fk_customer_comments_quotation_line_id_quotation_line_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_comments'))
    )
    op.create_index(op.f('ix_customer_comments_company_id'), 'customer_comments', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_comments_customer_id'), 'customer_comments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_comments_quotation_id'), 'customer_comments', ['quotation_id'], unique=False)
    op.create_table('negotiation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('quotation_line_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('requested_value', sa.String(length=255), nullable=False),
    sa.Column('current_value', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_negotiation_requests_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_negotiation_requests_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_negotiation_requests_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_line_items.id'], name=op.f('fk_negotiation_requests_quotation_line_id_quotation_line_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiation_requests'))
    )
    op.create_index(op.f('ix_negotiation_requests_company_id'), 'negotiation_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_customer_id'), 'negotiation_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_quotation_id'), 'negotiation_requests', ['quotation_id'], unique=False)
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_customer_id_customers'), 'users', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_customer_id_customers'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_column('users', 'customer_id')
    op.drop_index(op.f('ix_negotiation_requests_quotation_id'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_customer_id'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_company_id'), table_name='negotiation_requests')
    op.drop_table('negotiation_requests')
    op.drop_index(op.f('ix_customer_comments_quotation_id'), table_name='customer_comments')
    op.drop_index(op.f('ix_customer_comments_customer_id'), table_name='customer_comments')
    op.drop_index(op.f('ix_customer_comments_company_id'), table_name='customer_comments')
    op.drop_table('customer_comments')
    op.drop_index(op.f('ix_negotiation_history_quotation_id'), table_name='negotiation_history')
    op.drop_index(op.f('ix_negotiation_history_customer_id'), table_name='negotiation_history')
    op.drop_index(op.f('ix_negotiation_history_company_id'), table_name='negotiation_history')
    op.drop_table('negotiation_history')
    op.drop_index(op.f('ix_customer_notifications_customer_id'), table_name='customer_notifications')
    op.drop_index(op.f('ix_customer_notifications_company_id'), table_name='customer_notifications')
    op.drop_table('customer_notifications')
    # ### end Alembic commands ###
