"""add_g21_discount_governance_phase_101_105

Revision ID: 642847a0a7ce
Revises: d0a50651987a
Create Date: 2026-09-05 17:17:43.270285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642847a0a7ce'
down_revision: Union[str, Sequence[str], None] = 'd0a50651987a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_discount_ceilings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('max_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_category_discount_ceilings_ck_cat_discount_ceiling_effective_dates')),
    sa.CheckConstraint('max_discount_percentage >= 0 AND max_discount_percentage <= 100', name=op.f('ck_category_discount_ceilings_ck_cat_discount_ceiling_range')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_category_discount_ceilings_category_id_product_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_category_discount_ceilings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_category_discount_ceilings_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_discount_ceilings'))
    )
    op.create_index(op.f('ix_category_discount_ceilings_category_id'), 'category_discount_ceilings', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_discount_ceilings_company_id'), 'category_discount_ceilings', ['company_id'], unique=False)
    op.create_index(op.f('ix_category_discount_ceilings_is_active'), 'category_discount_ceilings', ['is_active'], unique=False)
    op.create_index('uq_cat_discount_ceilings_active', 'category_discount_ceilings', ['company_id', 'category_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('customer_discount_ceilings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('max_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_customer_discount_ceilings_ck_cust_discount_ceiling_effective_dates')),
    sa.CheckConstraint('max_discount_percentage >= 0 AND max_discount_percentage <= 100', name=op.f('ck_customer_discount_ceilings_ck_cust_discount_ceiling_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_discount_ceilings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_discount_ceilings_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_discount_ceilings_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_discount_ceilings'))
    )
    op.create_index(op.f('ix_customer_discount_ceilings_company_id'), 'customer_discount_ceilings', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_discount_ceilings_customer_id'), 'customer_discount_ceilings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_discount_ceilings_is_active'), 'customer_discount_ceilings', ['is_active'], unique=False)
    op.create_index('uq_cust_discount_ceilings_active', 'customer_discount_ceilings', ['company_id', 'customer_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('discount_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_discount_ceiling', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_discount_ceiling >= 0 AND default_discount_ceiling <= 100', name=op.f('ck_discount_configurations_ck_discount_config_ceiling_range')),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_discount_configurations_ck_discount_config_effective_dates')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_discount_configurations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_discount_configurations_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_configurations'))
    )
    op.create_index('ix_discount_config_company_active', 'discount_configurations', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_discount_configurations_company_id'), 'discount_configurations', ['company_id'], unique=False)
    op.create_index(op.f('ix_discount_configurations_is_active'), 'discount_configurations', ['is_active'], unique=False)
    op.create_table('product_discount_ceilings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('max_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_product_discount_ceilings_ck_prod_discount_ceiling_effective_dates')),
    sa.CheckConstraint('max_discount_percentage >= 0 AND max_discount_percentage <= 100', name=op.f('ck_product_discount_ceilings_ck_prod_discount_ceiling_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_discount_ceilings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_discount_ceilings_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_discount_ceilings_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_discount_ceilings'))
    )
    op.create_index(op.f('ix_product_discount_ceilings_company_id'), 'product_discount_ceilings', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_discount_ceilings_is_active'), 'product_discount_ceilings', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_discount_ceilings_product_id'), 'product_discount_ceilings', ['product_id'], unique=False)
    op.create_index('uq_prod_discount_ceilings_active', 'product_discount_ceilings', ['company_id', 'product_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('sales_rep_authority_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_authorized_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name=op.f('ck_sales_rep_authority_limits_ck_sales_rep_auth_limit_effective_dates')),
    sa.CheckConstraint('max_authorized_discount >= 0 AND max_authorized_discount <= 100', name=op.f('ck_sales_rep_authority_limits_ck_sales_rep_auth_limit_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sales_rep_authority_limits_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sales_rep_authority_limits_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_rep_authority_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_rep_authority_limits'))
    )
    op.create_index(op.f('ix_sales_rep_authority_limits_company_id'), 'sales_rep_authority_limits', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_rep_authority_limits_is_active'), 'sales_rep_authority_limits', ['is_active'], unique=False)
    op.create_index(op.f('ix_sales_rep_authority_limits_user_id'), 'sales_rep_authority_limits', ['user_id'], unique=False)
    op.create_index('uq_sales_rep_auth_limits_active', 'sales_rep_authority_limits', ['company_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sales_rep_auth_limits_active', table_name='sales_rep_authority_limits', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_sales_rep_authority_limits_user_id'), table_name='sales_rep_authority_limits')
    op.drop_index(op.f('ix_sales_rep_authority_limits_is_active'), table_name='sales_rep_authority_limits')
    op.drop_index(op.f('ix_sales_rep_authority_limits_company_id'), table_name='sales_rep_authority_limits')
    op.drop_table('sales_rep_authority_limits')
    op.drop_index('uq_prod_discount_ceilings_active', table_name='product_discount_ceilings', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_product_discount_ceilings_product_id'), table_name='product_discount_ceilings')
    op.drop_index(op.f('ix_product_discount_ceilings_is_active'), table_name='product_discount_ceilings')
    op.drop_index(op.f('ix_product_discount_ceilings_company_id'), table_name='product_discount_ceilings')
    op.drop_table('product_discount_ceilings')
    op.drop_index(op.f('ix_discount_configurations_is_active'), table_name='discount_configurations')
    op.drop_index(op.f('ix_discount_configurations_company_id'), table_name='discount_configurations')
    op.drop_index('ix_discount_config_company_active', table_name='discount_configurations')
    op.drop_table('discount_configurations')
    op.drop_index('uq_cust_discount_ceilings_active', table_name='customer_discount_ceilings', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_customer_discount_ceilings_is_active'), table_name='customer_discount_ceilings')
    op.drop_index(op.f('ix_customer_discount_ceilings_customer_id'), table_name='customer_discount_ceilings')
    op.drop_index(op.f('ix_customer_discount_ceilings_company_id'), table_name='customer_discount_ceilings')
    op.drop_table('customer_discount_ceilings')
    op.drop_index('uq_cat_discount_ceilings_active', table_name='category_discount_ceilings', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_category_discount_ceilings_is_active'), table_name='category_discount_ceilings')
    op.drop_index(op.f('ix_category_discount_ceilings_company_id'), table_name='category_discount_ceilings')
    op.drop_index(op.f('ix_category_discount_ceilings_category_id'), table_name='category_discount_ceilings')
    op.drop_table('category_discount_ceilings')
    # ### end Alembic commands ###
