"""add_g17_recurring_frequency_and_inventory

Revision ID: 6e9b573965f6
Revises: 89187043088e
Create Date: 2026-09-05 15:09:09.568368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9b573965f6'
down_revision: Union[str, Sequence[str], None] = '89187043088e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('recurring_frequency', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('inventory_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'inventory_quantity')
    op.drop_column('products', 'recurring_frequency')
    # ### end Alembic commands ###
