"""create_g13_customer_discount_and_payment_history

Revision ID: 792cf31a43e3
Revises: bd06814ec088
Create Date: 2026-09-05 14:05:44.538585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792cf31a43e3'
down_revision: Union[str, Sequence[str], None] = 'bd06814ec088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_discount_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('discount_code', sa.String(length=50), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deal_reference', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_discount_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_discount_history_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_discount_history'))
    )
    op.create_index(op.f('ix_customer_discount_history_company_id'), 'customer_discount_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_discount_history_customer_id'), 'customer_discount_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_discount_history_discount_code'), 'customer_discount_history', ['discount_code'], unique=False)
    op.create_table('customer_payment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_payment_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_payment_history_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_payment_history'))
    )
    op.create_index(op.f('ix_customer_payment_history_company_id'), 'customer_payment_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_payment_history_customer_id'), 'customer_payment_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_payment_history_payment_reference'), 'customer_payment_history', ['payment_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_payment_history_payment_reference'), table_name='customer_payment_history')
    op.drop_index(op.f('ix_customer_payment_history_customer_id'), table_name='customer_payment_history')
    op.drop_index(op.f('ix_customer_payment_history_company_id'), table_name='customer_payment_history')
    op.drop_table('customer_payment_history')
    op.drop_index(op.f('ix_customer_discount_history_discount_code'), table_name='customer_discount_history')
    op.drop_index(op.f('ix_customer_discount_history_customer_id'), table_name='customer_discount_history')
    op.drop_index(op.f('ix_customer_discount_history_company_id'), table_name='customer_discount_history')
    op.drop_table('customer_discount_history')
    # ### end Alembic commands ###
