"""add_warehouse_priority_phase_091

Revision ID: 85e26b2d6704
Revises: b322831bdbb0
Create Date: 2026-09-05 15:45:20.094452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e26b2d6704'
down_revision: Union[str, Sequence[str], None] = 'b322831bdbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('priority', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_warehouses_priority'), 'warehouses', ['priority'], unique=False)
    op.create_check_constraint('ck_warehouses_priority_positive', 'warehouses', 'priority >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_warehouses_priority_positive', 'warehouses', type_='check')
    op.drop_index(op.f('ix_warehouses_priority'), table_name='warehouses')
    op.drop_column('warehouses', 'priority')
    # ### end Alembic commands ###
