"""add_b09_quotation_tables

Revision ID: 9c20d262e0d7
Revises: 1e5fe8eb16c3
Create Date: 2026-09-06 02:07:33.588817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c20d262e0d7'
down_revision: Union[str, Sequence[str], None] = '1e5fe8eb16c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Author/Sales representative who created the quotation'),
    sa.Column('quotation_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, comment='Sum of gross line subtotals before discounts'),
    sa.Column('line_discount_total', sa.Numeric(precision=14, scale=2), nullable=False, comment='Aggregated sum of all line item discounts'),
    sa.Column('overall_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Quotation-level overall discount percentage (Phase 194)'),
    sa.Column('overall_discount_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Quotation-level overall discount monetary amount (Phase 194)'),
    sa.Column('total_discount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Combined total discounts (line discounts + overall discount)'),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Net taxable base after all discounts applied (Phase 192)'),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Aggregated tax amount (Phase 192)'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Final grand total amount payable (taxable + tax)'),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False, comment='Aggregated product cost across all line items'),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total net revenue excluding tax minus total cost'),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Gross profit margin percentage'),
    sa.Column('is_negative_margin', sa.Boolean(), nullable=False, comment='Flag indicating quotation has negative gross profit'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quotations_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quotations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('company_id', 'quotation_number', name='uq_quotations_company_quotation_number')
    )
    op.create_index(op.f('ix_quotations_company_id'), 'quotations', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index(op.f('ix_quotations_user_id'), 'quotations', ['user_id'], unique=False)
    op.create_table('quotation_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False, comment='Ordered quantity (Phase 190)'),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False, comment='Selling unit price before discount (Phase 191)'),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False, comment='Product unit cost at time of quotation (Phase 195)'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Line item discount percentage (Phase 193)'),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Line item discount monetary amount (Phase 193)'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Line tax percentage rate (Phase 192)'),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Calculated line tax monetary amount (Phase 192)'),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, comment='Gross line amount (quantity * unit_price)'),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Line amount after line discount (subtotal - discount_amount)'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Line amount including tax (net_amount + tax_amount)'),
    sa.Column('line_cost', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total cost for line (quantity * unit_cost)'),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False, comment='Line gross profit (net_amount - line_cost)'),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Line gross margin percentage'),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quotation_line_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_line_items_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_line_items'))
    )
    op.create_index(op.f('ix_quotation_line_items_product_id'), 'quotation_line_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotation_line_items_quotation_id'), 'quotation_line_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_line_items_quotation_id'), table_name='quotation_line_items')
    op.drop_index(op.f('ix_quotation_line_items_product_id'), table_name='quotation_line_items')
    op.drop_table('quotation_line_items')
    op.drop_index(op.f('ix_quotations_user_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_company_id'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###
