"""create_warehouse_stocks_phases_086_090

Revision ID: b322831bdbb0
Revises: 6e9b573965f6
Create Date: 2026-09-05 15:28:50.855282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b322831bdbb0'
down_revision: Union[str, Sequence[str], None] = '6e9b573965f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_warehouse_stocks_ck_warehouse_stocks_qty_non_negative')),
    sa.CheckConstraint('reserved_quantity <= quantity', name=op.f('ck_warehouse_stocks_ck_warehouse_stocks_reserved_lte_qty')),
    sa.CheckConstraint('reserved_quantity >= 0', name=op.f('ck_warehouse_stocks_ck_warehouse_stocks_reserved_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_warehouse_stocks_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_warehouse_stocks_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_stocks')),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_warehouse_stocks_warehouse_product')
    )
    op.create_index(op.f('ix_warehouse_stocks_product_id'), 'warehouse_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_warehouse_stocks_warehouse_id'), 'warehouse_stocks', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_stocks_warehouse_id'), table_name='warehouse_stocks')
    op.drop_index(op.f('ix_warehouse_stocks_product_id'), table_name='warehouse_stocks')
    op.drop_table('warehouse_stocks')
    # ### end Alembic commands ###
