"""create_g12_customer_history_models

Revision ID: bd06814ec088
Revises: d90b92e011e8
Create Date: 2026-09-05 13:48:17.284969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd06814ec088'
down_revision: Union[str, Sequence[str], None] = 'd90b92e011e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_deal_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('deal_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('deal_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sales_rep_name', sa.String(length=100), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_deal_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_deal_history_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_deal_history'))
    )
    op.create_index(op.f('ix_customer_deal_history_company_id'), 'customer_deal_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_deal_history_customer_id'), 'customer_deal_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_deal_history_deal_code'), 'customer_deal_history', ['deal_code'], unique=False)
    op.create_table('customer_purchase_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_purchase_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_purchase_history_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_purchase_history'))
    )
    op.create_index(op.f('ix_customer_purchase_history_company_id'), 'customer_purchase_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_customer_id'), 'customer_purchase_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_order_number'), 'customer_purchase_history', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_purchase_history_order_number'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_purchase_history_customer_id'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_purchase_history_company_id'), table_name='customer_purchase_history')
    op.drop_table('customer_purchase_history')
    op.drop_index(op.f('ix_customer_deal_history_deal_code'), table_name='customer_deal_history')
    op.drop_index(op.f('ix_customer_deal_history_customer_id'), table_name='customer_deal_history')
    op.drop_index(op.f('ix_customer_deal_history_company_id'), table_name='customer_deal_history')
    op.drop_table('customer_deal_history')
    # ### end Alembic commands ###
