"""add_g20_inventory_fulfillment_phase_096_100

Revision ID: d0a50651987a
Revises: 85e26b2d6704
Create Date: 2026-09-05 16:19:36.690948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a50651987a'
down_revision: Union[str, Sequence[str], None] = '85e26b2d6704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backorders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('backordered_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_quantity >= 0', name=op.f('ck_backorders_ck_backorders_allocated_qty_non_negative')),
    sa.CheckConstraint('backordered_quantity = requested_quantity - allocated_quantity', name=op.f('ck_backorders_ck_backorders_backordered_calc')),
    sa.CheckConstraint('backordered_quantity > 0', name=op.f('ck_backorders_ck_backorders_backordered_qty_positive')),
    sa.CheckConstraint('requested_quantity > 0', name=op.f('ck_backorders_ck_backorders_requested_qty_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_backorders_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_backorders_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backorders'))
    )
    op.create_index(op.f('ix_backorders_company_id'), 'backorders', ['company_id'], unique=False)
    op.create_index('ix_backorders_company_status', 'backorders', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_backorders_id'), 'backorders', ['id'], unique=False)
    op.create_index(op.f('ix_backorders_product_id'), 'backorders', ['product_id'], unique=False)
    op.create_index(op.f('ix_backorders_status'), 'backorders', ['status'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_inventory_alerts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_alerts_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_alerts_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_alerts'))
    )
    op.create_index(op.f('ix_inventory_alerts_alert_type'), 'inventory_alerts', ['alert_type'], unique=False)
    op.create_index('ix_inventory_alerts_company_active', 'inventory_alerts', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_company_id'), 'inventory_alerts', ['company_id'], unique=False)
    op.create_index('ix_inventory_alerts_dedup', 'inventory_alerts', ['company_id', 'product_id', 'warehouse_id', 'alert_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_id'), 'inventory_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_is_active'), 'inventory_alerts', ['is_active'], unique=False)
    op.create_index('ix_inventory_alerts_product_active', 'inventory_alerts', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_product_id'), 'inventory_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_warehouse_id'), 'inventory_alerts', ['warehouse_id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('fulfilled_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('backorder_id', sa.UUID(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fulfilled_quantity <= requested_quantity', name=op.f('ck_fulfillments_ck_fulfillments_fulfilled_lte_requested')),
    sa.CheckConstraint('fulfilled_quantity >= 0', name=op.f('ck_fulfillments_ck_fulfillments_fulfilled_qty_non_negative')),
    sa.CheckConstraint('remaining_quantity = requested_quantity - fulfilled_quantity', name=op.f('ck_fulfillments_ck_fulfillments_remaining_calc')),
    sa.CheckConstraint('remaining_quantity >= 0', name=op.f('ck_fulfillments_ck_fulfillments_remaining_qty_non_negative')),
    sa.CheckConstraint('requested_quantity > 0', name=op.f('ck_fulfillments_ck_fulfillments_requested_qty_positive')),
    sa.ForeignKeyConstraint(['backorder_id'], ['backorders.id'], name=op.f('fk_fulfillments_backorder_id_backorders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fulfillments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_fulfillments_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillments'))
    )
    op.create_index(op.f('ix_fulfillments_backorder_id'), 'fulfillments', ['backorder_id'], unique=False)
    op.create_index('ix_fulfillments_company_delivery_status', 'fulfillments', ['company_id', 'delivery_status'], unique=False)
    op.create_index(op.f('ix_fulfillments_company_id'), 'fulfillments', ['company_id'], unique=False)
    op.create_index('ix_fulfillments_company_status', 'fulfillments', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_fulfillments_delivery_status'), 'fulfillments', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_fulfillments_id'), 'fulfillments', ['id'], unique=False)
    op.create_index(op.f('ix_fulfillments_product_id'), 'fulfillments', ['product_id'], unique=False)
    op.create_index(op.f('ix_fulfillments_status'), 'fulfillments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulfillments_status'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_product_id'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_id'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_delivery_status'), table_name='fulfillments')
    op.drop_index('ix_fulfillments_company_status', table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_company_id'), table_name='fulfillments')
    op.drop_index('ix_fulfillments_company_delivery_status', table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_backorder_id'), table_name='fulfillments')
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_inventory_alerts_warehouse_id'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_product_id'), table_name='inventory_alerts')
    op.drop_index('ix_inventory_alerts_product_active', table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_is_active'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_id'), table_name='inventory_alerts')
    op.drop_index('ix_inventory_alerts_dedup', table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_company_id'), table_name='inventory_alerts')
    op.drop_index('ix_inventory_alerts_company_active', table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_alert_type'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('ix_backorders_status'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_product_id'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_id'), table_name='backorders')
    op.drop_index('ix_backorders_company_status', table_name='backorders')
    op.drop_index(op.f('ix_backorders_company_id'), table_name='backorders')
    op.drop_table('backorders')
    # ### end Alembic commands ###
