"""add_b11_deal_tables_and_columns

Revision ID: e909fd4f9ed6
Revises: f91ec4d9c5f2
Create Date: 2026-09-06 02:49:35.419921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e909fd4f9ed6'
down_revision: Union[str, Sequence[str], None] = 'f91ec4d9c5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_deal_activities_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deal_activities_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['customer_deal_history.id'], name=op.f('fk_deal_activities_deal_id_customer_deal_history'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_activities'))
    )
    op.create_index(op.f('ix_deal_activities_activity_type'), 'deal_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_deal_activities_actor_id'), 'deal_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_deal_activities_company_id'), 'deal_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_activities_created_at'), 'deal_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_deal_activities_deal_id'), 'deal_activities', ['deal_id'], unique=False)
    op.create_table('deal_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quotation_line_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name=op.f('ck_deal_products_chk_deal_product_discount_pct_range')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_deal_products_chk_deal_product_quantity_pos')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_deal_products_chk_deal_product_tax_rate_range')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_deal_products_chk_deal_product_unit_cost_nonneg')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_deal_products_chk_deal_product_unit_price_nonneg')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deal_products_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['customer_deal_history.id'], name=op.f('fk_deal_products_deal_id_customer_deal_history'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_deal_products_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_line_item_id'], ['quotation_line_items.id'], name=op.f('fk_deal_products_quotation_line_item_id_quotation_line_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_products')),
    sa.UniqueConstraint('deal_id', 'product_id', name='uq_deal_products_deal_product')
    )
    op.create_index(op.f('ix_deal_products_company_id'), 'deal_products', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_products_deal_id'), 'deal_products', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_products_product_id'), 'deal_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_deal_products_quotation_line_item_id'), 'deal_products', ['quotation_line_item_id'], unique=False)
    op.add_column('customer_deal_history', sa.Column('stage', sa.String(length=50), server_default='NEW', nullable=False))
    op.add_column('customer_deal_history', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('customer_deal_history', sa.Column('quotation_id', sa.UUID(), nullable=True))
    op.add_column('customer_deal_history', sa.Column('quotation_version', sa.Integer(), nullable=True))
    op.add_column('customer_deal_history', sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('total_cost', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('margin_percentage', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('probability', sa.Integer(), server_default='50', nullable=False))
    op.add_column('customer_deal_history', sa.Column('expected_revenue', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
    op.add_column('customer_deal_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_customer_deal_history_owner_id'), 'customer_deal_history', ['owner_id'], unique=False)
    op.create_index(op.f('ix_customer_deal_history_quotation_id'), 'customer_deal_history', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_customer_deal_history_stage'), 'customer_deal_history', ['stage'], unique=False)
    op.create_foreign_key(op.f('fk_customer_deal_history_owner_id_users'), 'customer_deal_history', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_customer_deal_history_quotation_id_quotations'), 'customer_deal_history', 'quotations', ['quotation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_customer_deal_history_quotation_id_quotations'), 'customer_deal_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_deal_history_owner_id_users'), 'customer_deal_history', type_='foreignkey')
    op.drop_index(op.f('ix_customer_deal_history_stage'), table_name='customer_deal_history')
    op.drop_index(op.f('ix_customer_deal_history_quotation_id'), table_name='customer_deal_history')
    op.drop_index(op.f('ix_customer_deal_history_owner_id'), table_name='customer_deal_history')
    op.drop_column('customer_deal_history', 'updated_at')
    op.drop_column('customer_deal_history', 'expected_revenue')
    op.drop_column('customer_deal_history', 'probability')
    op.drop_column('customer_deal_history', 'margin_percentage')
    op.drop_column('customer_deal_history', 'gross_profit')
    op.drop_column('customer_deal_history', 'total_cost')
    op.drop_column('customer_deal_history', 'tax_amount')
    op.drop_column('customer_deal_history', 'discount_percent')
    op.drop_column('customer_deal_history', 'discount_amount')
    op.drop_column('customer_deal_history', 'subtotal')
    op.drop_column('customer_deal_history', 'quotation_version')
    op.drop_column('customer_deal_history', 'quotation_id')
    op.drop_column('customer_deal_history', 'owner_id')
    op.drop_column('customer_deal_history', 'stage')
    op.drop_index(op.f('ix_deal_products_quotation_line_item_id'), table_name='deal_products')
    op.drop_index(op.f('ix_deal_products_product_id'), table_name='deal_products')
    op.drop_index(op.f('ix_deal_products_deal_id'), table_name='deal_products')
    op.drop_index(op.f('ix_deal_products_company_id'), table_name='deal_products')
    op.drop_table('deal_products')
    op.drop_index(op.f('ix_deal_activities_deal_id'), table_name='deal_activities')
    op.drop_index(op.f('ix_deal_activities_created_at'), table_name='deal_activities')
    op.drop_index(op.f('ix_deal_activities_company_id'), table_name='deal_activities')
    op.drop_index(op.f('ix_deal_activities_actor_id'), table_name='deal_activities')
    op.drop_index(op.f('ix_deal_activities_activity_type'), table_name='deal_activities')
    op.drop_table('deal_activities')
    # ### end Alembic commands ###
