"""add_b06_approval_execution_phases_156_165

Revision ID: ed5e9db9b059
Revises: 3d9772928f35
Create Date: 2026-09-06 00:39:12.648044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5e9db9b059'
down_revision: Union[str, Sequence[str], None] = '3d9772928f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('deal_reference', sa.String(length=100), nullable=False),
    sa.Column('deal_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('requested_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('required_level', sa.String(length=50), nullable=False),
    sa.Column('required_chain_type', sa.String(length=50), nullable=False),
    sa.Column('current_step_number', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('blended_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('blended_risk_classification', sa.String(length=50), nullable=False),
    sa.Column('routing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('final_actioned_by_id', sa.UUID(), nullable=True),
    sa.Column('final_actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_requests_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_approval_requests_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['final_actioned_by_id'], ['users.id'], name=op.f('fk_approval_requests_final_actioned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_approval_requests_submitted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index('ix_approval_requests_company_deal', 'approval_requests', ['company_id', 'deal_reference'], unique=False)
    op.create_index(op.f('ix_approval_requests_company_id'), 'approval_requests', ['company_id'], unique=False)
    op.create_index('ix_approval_requests_company_status', 'approval_requests', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_requests_customer_id'), 'approval_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_deal_reference'), 'approval_requests', ['deal_reference'], unique=False)
    op.create_index(op.f('ix_approval_requests_expires_at'), 'approval_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('approval_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('deal_reference', sa.String(length=100), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('approval_level', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_audit_logs_approval_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_audit_logs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_audit_logs'))
    )
    op.create_index(op.f('ix_approval_audit_logs_approval_request_id'), 'approval_audit_logs', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_audit_logs_company_id'), 'approval_audit_logs', ['company_id'], unique=False)
    op.create_index('ix_approval_audit_logs_company_req', 'approval_audit_logs', ['company_id', 'approval_request_id'], unique=False)
    op.create_index('ix_approval_audit_logs_deal', 'approval_audit_logs', ['company_id', 'deal_reference'], unique=False)
    op.create_index(op.f('ix_approval_audit_logs_deal_reference'), 'approval_audit_logs', ['deal_reference'], unique=False)
    op.create_table('approval_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('deal_reference', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_role', sa.String(length=100), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_notifications_approval_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_notifications_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_approval_notifications_recipient_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_notifications'))
    )
    op.create_index('ix_approval_notif_company_read', 'approval_notifications', ['company_id', 'is_read'], unique=False)
    op.create_index('ix_approval_notif_company_role', 'approval_notifications', ['company_id', 'recipient_role'], unique=False)
    op.create_index(op.f('ix_approval_notifications_approval_request_id'), 'approval_notifications', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_notifications_company_id'), 'approval_notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_approval_notifications_deal_reference'), 'approval_notifications', ['deal_reference'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('required_level', sa.String(length=50), nullable=False),
    sa.Column('assigned_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_by_id', sa.UUID(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('escalated_to_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actioned_by_id'], ['users.id'], name=op.f('fk_approval_steps_actioned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_steps_approval_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_approval_steps_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps'))
    )
    op.create_index(op.f('ix_approval_steps_approval_request_id'), 'approval_steps', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_company_id'), 'approval_steps', ['company_id'], unique=False)
    op.create_index('ix_approval_steps_company_status', 'approval_steps', ['company_id', 'status'], unique=False)
    op.create_index('ix_approval_steps_request_step', 'approval_steps', ['approval_request_id', 'step_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_steps_request_step', table_name='approval_steps')
    op.drop_index('ix_approval_steps_company_status', table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_company_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_approval_request_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_approval_notifications_deal_reference'), table_name='approval_notifications')
    op.drop_index(op.f('ix_approval_notifications_company_id'), table_name='approval_notifications')
    op.drop_index(op.f('ix_approval_notifications_approval_request_id'), table_name='approval_notifications')
    op.drop_index('ix_approval_notif_company_role', table_name='approval_notifications')
    op.drop_index('ix_approval_notif_company_read', table_name='approval_notifications')
    op.drop_table('approval_notifications')
    op.drop_index(op.f('ix_approval_audit_logs_deal_reference'), table_name='approval_audit_logs')
    op.drop_index('ix_approval_audit_logs_deal', table_name='approval_audit_logs')
    op.drop_index('ix_approval_audit_logs_company_req', table_name='approval_audit_logs')
    op.drop_index(op.f('ix_approval_audit_logs_company_id'), table_name='approval_audit_logs')
    op.drop_index(op.f('ix_approval_audit_logs_approval_request_id'), table_name='approval_audit_logs')
    op.drop_table('approval_audit_logs')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_expires_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_deal_reference'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_customer_id'), table_name='approval_requests')
    op.drop_index('ix_approval_requests_company_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_company_id'), table_name='approval_requests')
    op.drop_index('ix_approval_requests_company_deal', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
