"""add_b10_quotation_lifecycle_tables

Revision ID: f91ec4d9c5f2
Revises: 9c20d262e0d7
Create Date: 2026-09-06 02:26:10.757979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f91ec4d9c5f2'
down_revision: Union[str, Sequence[str], None] = '9c20d262e0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_send_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotation_send_logs_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_send_logs_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_quotation_send_logs_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_send_logs'))
    )
    op.create_index(op.f('ix_quotation_send_logs_company_id'), 'quotation_send_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotation_send_logs_quotation_id'), 'quotation_send_logs', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_send_logs_tracking_token'), 'quotation_send_logs', ['tracking_token'], unique=True)
    op.create_table('quotation_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotation_versions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_quotation_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_versions_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_versions')),
    sa.UniqueConstraint('quotation_id', 'version_number', name='uq_quotation_versions_quote_ver')
    )
    op.create_index(op.f('ix_quotation_versions_company_id'), 'quotation_versions', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotation_versions_quotation_id'), 'quotation_versions', ['quotation_id'], unique=False)
    op.add_column('quotations', sa.Column('version_number', sa.Integer(), server_default='1', nullable=False, comment='Active version number of the quotation (Phase 197)'))
    op.add_column('quotations', sa.Column('approval_request_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('accepted_by_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('acceptance_notes', sa.Text(), nullable=True))
    op.add_column('quotations', sa.Column('rejected_by_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('quotations', sa.Column('converted_deal_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('quotations', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Expiration timestamp (Phase 198)',
               existing_nullable=True)
    op.create_index(op.f('ix_quotations_approval_request_id'), 'quotations', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_quotations_converted_deal_id'), 'quotations', ['converted_deal_id'], unique=False)
    op.create_foreign_key(op.f('fk_quotations_accepted_by_id_users'), 'quotations', 'users', ['accepted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_rejected_by_id_users'), 'quotations', 'users', ['rejected_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_converted_deal_id_customer_deal_history'), 'quotations', 'customer_deal_history', ['converted_deal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quotations_approval_request_id_approval_requests'), 'quotations', 'approval_requests', ['approval_request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quotations_approval_request_id_approval_requests'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_converted_deal_id_customer_deal_history'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_rejected_by_id_users'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_accepted_by_id_users'), 'quotations', type_='foreignkey')
    op.drop_index(op.f('ix_quotations_converted_deal_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_approval_request_id'), table_name='quotations')
    op.alter_column('quotations', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Expiration timestamp (Phase 198)',
               existing_nullable=True)
    op.drop_column('quotations', 'viewed_at')
    op.drop_column('quotations', 'sent_at')
    op.drop_column('quotations', 'converted_at')
    op.drop_column('quotations', 'converted_deal_id')
    op.drop_column('quotations', 'rejection_reason')
    op.drop_column('quotations', 'rejected_at')
    op.drop_column('quotations', 'rejected_by_id')
    op.drop_column('quotations', 'acceptance_notes')
    op.drop_column('quotations', 'accepted_at')
    op.drop_column('quotations', 'accepted_by_id')
    op.drop_column('quotations', 'approval_request_id')
    op.drop_column('quotations', 'version_number')
    op.drop_index(op.f('ix_quotation_versions_quotation_id'), table_name='quotation_versions')
    op.drop_index(op.f('ix_quotation_versions_company_id'), table_name='quotation_versions')
    op.drop_table('quotation_versions')
    op.drop_index(op.f('ix_quotation_send_logs_tracking_token'), table_name='quotation_send_logs')
    op.drop_index(op.f('ix_quotation_send_logs_quotation_id'), table_name='quotation_send_logs')
    op.drop_index(op.f('ix_quotation_send_logs_company_id'), table_name='quotation_send_logs')
    op.drop_table('quotation_send_logs')
    # ### end Alembic commands ###
